[package]
name = "flipflop"
version = "0.1.0"
authors = ["Adam Gausmann <agausmann@fastmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
futures-executor = "0.3"
futures-util = "0.3"
wgpu = "0.7"
wgpu_glyph = "0.11"
winit = "0.24"
